[package]
name = "catapult"
version = "0.1.1"
authors = ["Pierre Baillet <pierre@baillet.name>"]

description = "Catapult sends you logs elsewhere"
keyworkds = ["network", "logs", "shipping", "logstash"]
readme = "README"
license= "MIT"

[dependencies]

serde = "*"
chrono = "*"
hyper = "*"
url = "*"
nom = "*"
docopt = "*"
time = "*"
