[package]
name = "catapult"
version = "0.1.0"
authors = ["Pierre Baillet <pierre@baillet.name>"]

description = "Reads json in stdin, sends everything to ES, validate slightly in the middle"
readme = "README"
license= "MIT"

[dependencies]

serde = "*"
chrono = "*"
hyper = "*"
url = "*"
nom = "*"
